plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable  # ← 新しいCopを自動で有効にする（任意だが推奨）

Naming/PredicatePrefix:
  Enabled: true
